services:
  bot:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    working_dir: /app/
    command: sh -c "alembic upgrade head && cd src && python -m dayz.presentation.bot.main"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  db:
    image: postgres:latest
    command: postgres -c 'max_connections=999'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgresql-data:/var/lib/postgresql
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin_panel:
    build:
      context: .
      dockerfile: deploy/app/Dockerfile
    working_dir: /app/src
    command: sh -c "python -m dayz.presentation.admin.main;"
    env_file:
      - .env
    depends_on:
      - db
      - bot
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - "8100:8100"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./deploy/grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    expose:
      - 3100
    volumes:
      - ./deploy/loki/config.yaml:/etc/loki/config.yaml:ro
    command: -config.file=/etc/loki/config.yaml

  alloy:
      image: grafana/alloy:latest
      volumes:
        - ./deploy/alloy/config.alloy:/etc/alloy/config.alloy
        - /var/run/docker.sock:/var/run/docker.sock:ro
      command: run /etc/alloy/config.alloy
      environment:
        - LOKI_URL=http://loki:3100/loki/api/v1/push
      restart: unless-stopped


volumes:
  postgresql-data:
  grafana-data: