"""Rename server table

Revision ID: 00a46c088bcb
Revises: e7fae4a892fa
Create Date: 2024-12-06 17:44:34.610945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a46c088bcb'
down_revision: Union[str, None] = 'e7fae4a892fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('servers', 'pvp_servers')
    op.create_index(op.f('ix_pvp_servers_id'), 'pvp_servers', ['id'], unique=False)
    op.drop_index('ix_servers_id', table_name='servers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('pvp_servers', 'servers')
    op.create_index('ix_servers_id', 'servers', ['id'], unique=False)
    op.drop_index(op.f('ix_pvp_servers_id'), table_name='pvp_servers')
    # ### end Alembic commands ###
