"""Update servers models

Revision ID: 42ccb579b063
Revises: 2d21bb6fc7aa
Create Date: 2025-12-02 22:51:00.909607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ccb579b063'
down_revision: Union[str, None] = '2d21bb6fc7aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pve_servers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pve_servers', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pve_servers', 'query_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pvp_servers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pvp_servers', 'port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pvp_servers', 'query_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pvp_servers', 'query_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pvp_servers', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pvp_servers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pve_servers', 'query_port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pve_servers', 'port',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pve_servers', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
