"""added forum_id, update message_id

Revision ID: e7fae4a892fa
Revises: 9da0370b7725
Create Date: 2024-05-18 15:35:40.610735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fae4a892fa'
down_revision: Union[str, None] = '9da0370b7725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('forum_id', sa.BIGINT(), nullable=True))
    op.alter_column('servers', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('servers', 'message_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('servers', 'forum_id')
    # ### end Alembic commands ###
